# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Pre-Requisites
    before: gem install stax
    init: cd ops/ && bundle install
    command: exit
