
tasks:
  - name: Install Dependencies
    init: cd ops/ && bundle install
    command: exit
  - name: Configure AWS EnvVars
    command: ./.gitpod/scripts/awsenv.sh && exit

vscode:
  extensions:
    - rebornix.ruby
